# Generated by Django 5.0.1 on 2024-01-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('user_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('inprogress', 'inprogress'), ('done', 'done')], default='pending', max_length=200)),
            ],
        ),
    ]
